# Generated by Django 4.1 on 2022-12-13 20:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_reserva_cantidadpersonas_alter_reserva_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='fecha_hora',
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='hora',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
